services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: django_web
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile-tasks
    container_name: django_q_worker
    restart: unless-stopped