# Generated by Django 5.0.6 on 2024-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hn_username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
