# Generated by Django 5.0.6 on 2024-06-23 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_user_hn_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
