# Generated by Django 5.0.6 on 2024-06-23 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_user_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
