# Generated by Django 5.0.6 on 2026-05-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_user_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muted_posts",
                        to="alerts.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "post_id")},
            },
        ),
    ]
